/* ============================================================
   script.js
   All interactive logic for the portfolio lives here.
   Nothing is inline in the HTML — everything is linked via
   <script src="script.js"></script> at the bottom of the page.
   ============================================================ */

// ---- Reusable helper function (used in more than one place) ----
// Logs a nicely-labeled debug message to the console.
function logDebug(label, data) {
  console.log(`[Portfolio Debug] ${label}:`, data);
}

// Runs once the page has fully loaded (onload-style event)
window.onload = function () {
  logDebug("Page status", "Portfolio loaded successfully");

  // 1. Welcome message using window.alert()
  window.alert("Welcome to my portfolio! Glad you're here 💜");

  // 2. Change the heading text using innerHTML
  const heading = document.getElementById("main-heading");
  heading.innerHTML = "Hey, thanks for stopping by! 👋";
  logDebug("Heading updated", heading.innerHTML);
};

// ---- Grab elements once, reuse everywhere ----
const themeBtn = document.getElementById("theme-toggle-btn");
const infoBtn = document.getElementById("info-btn");
const styleBtn = document.getElementById("style-btn");
const infoBox = document.getElementById("info-box");
const aboutText = document.getElementById("about-text");

// 3. Theme toggle button (Light / Dark Mode) — onclick event
themeBtn.addEventListener("click", function () {
  document.body.classList.toggle("dark-mode");

  const isDark = document.body.classList.contains("dark-mode");
  themeBtn.textContent = isDark
    ? "☀️ Switch to Light Mode"
    : "🌙 Toggle Light / Dark Mode";

  logDebug("Theme toggled", isDark ? "Dark mode ON" : "Dark mode OFF");
});

// 4. Button that displays personal info when clicked
infoBtn.addEventListener("click", function () {
  showPersonalInfo();
});

// Reusable function: builds and displays the personal info block
function showPersonalInfo() {
  const isVisible = infoBox.style.display === "block";

  if (isVisible) {
    infoBox.style.display = "none";
    logDebug("Info box", "Hidden");
    return;
  }

  infoBox.innerHTML = `
    <strong>Name:</strong> Your Name Here<br>
    <strong>Role:</strong> Aspiring Web Developer<br>
    <strong>Fun Fact:</strong> This whole box was generated by JavaScript!
  `;
  infoBox.style.display = "block";
  logDebug("Info box", "Shown");
}

// 5. Modify the style of an element (font size, color, background)
styleBtn.addEventListener("click", function () {
  restyleCard();
});

// Reusable function: cycles the "About Me" card through a few pastel looks
let styleStep = 0;
function restyleCard() {
  const styles = [
    { background: "#ffe6f0", color: "#7a4a5a", fontSize: "1.05rem" },
    { background: "#e6f7ff", color: "#3a5a6a", fontSize: "1.15rem" },
    { background: "#f0ffe6", color: "#4a6a3a", fontSize: "1rem" }
  ];

  styleStep = (styleStep + 1) % styles.length;
  const chosen = styles[styleStep];

  aboutText.style.background = chosen.background;
  aboutText.style.color = chosen.color;
  aboutText.style.fontSize = chosen.fontSize;
  aboutText.style.padding = "10px";
  aboutText.style.borderRadius = "10px";
  aboutText.style.transition = "all 0.4s ease";

  logDebug("About text restyled", chosen);
}

// Example of onchange-style event: log when the window is resized
// (extra touch, shows another kind of event trigger)
window.addEventListener("resize", function () {
  logDebug("Window resized", `${window.innerWidth}px wide`);
});
